module.exports = [
'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'W                WW                              WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'W  @        W          W        WW               WWWWWWW                WWWWWWWW',
'W          WWW        WW        WW                         WWWWWW       WWWWWWWW',
'W  W  W     W      WWWWWWW      WW               WWWWWWWWWWWWWWWWWW   WWWWWWWWWW',
'W                      WW       WW               WWWWWWWWWWWWWWWWW        WWWWWW',
'W     WWWW           W          WW               WWWWWWWWWWWWWWWWWWWWW     WWWWW',
'W                                                WWWWWWWWWWWWWWWWWWWWWWWWW WWWWW',
'W     WWWWW      W  WWW        WW                WWWWWWWWWWWWWWWWWWWWWWWWW WWWWW',
'W         W      W  W W                          WWWWWWWWWWWWWWWWWWWWWWWWW WWWWW',
'W         WWWW   W  WWW                                                        W',
'W         WW     W                                                             W',
'W          W     W                                                             W',
'W          WWWWWWW                                                             W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'W                                                                              W',
'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
];